
package beltran_recu;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "recu_beltran_web_operaciones_9a", targetNamespace = "http://beltran_recu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecuBeltranWebOperaciones9A {


    /**
     * 
     * @param densidad
     * @param volumen
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularMasa", targetNamespace = "http://beltran_recu/", className = "beltran_recu.CalcularMasa")
    @ResponseWrapper(localName = "calcularMasaResponse", targetNamespace = "http://beltran_recu/", className = "beltran_recu.CalcularMasaResponse")
    @Action(input = "http://beltran_recu/recu_beltran_web_operaciones_9a/calcularMasaRequest", output = "http://beltran_recu/recu_beltran_web_operaciones_9a/calcularMasaResponse")
    public double calcularMasa(
        @WebParam(name = "densidad", targetNamespace = "")
        double densidad,
        @WebParam(name = "volumen", targetNamespace = "")
        double volumen);

}
