
package beltran_recu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "recu_beltran_web_operaciones_9a", targetNamespace = "http://beltran_recu/", wsdlLocation = "http://localhost:8080/recu_beltran_9a/recu_beltran_web_operaciones_9a?wsdl")
public class RecuBeltranWebOperaciones9A_Service
    extends Service
{

    private static final URL RECUBELTRANWEBOPERACIONES9A_WSDL_LOCATION;
    private static final WebServiceException RECUBELTRANWEBOPERACIONES9A_EXCEPTION;
    private static final QName RECUBELTRANWEBOPERACIONES9A_QNAME = new QName("http://beltran_recu/", "recu_beltran_web_operaciones_9a");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/recu_beltran_9a/recu_beltran_web_operaciones_9a?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECUBELTRANWEBOPERACIONES9A_WSDL_LOCATION = url;
        RECUBELTRANWEBOPERACIONES9A_EXCEPTION = e;
    }

    public RecuBeltranWebOperaciones9A_Service() {
        super(__getWsdlLocation(), RECUBELTRANWEBOPERACIONES9A_QNAME);
    }

    public RecuBeltranWebOperaciones9A_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECUBELTRANWEBOPERACIONES9A_QNAME, features);
    }

    public RecuBeltranWebOperaciones9A_Service(URL wsdlLocation) {
        super(wsdlLocation, RECUBELTRANWEBOPERACIONES9A_QNAME);
    }

    public RecuBeltranWebOperaciones9A_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECUBELTRANWEBOPERACIONES9A_QNAME, features);
    }

    public RecuBeltranWebOperaciones9A_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuBeltranWebOperaciones9A_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecuBeltranWebOperaciones9A
     */
    @WebEndpoint(name = "recu_beltran_web_operaciones_9aPort")
    public RecuBeltranWebOperaciones9A getRecuBeltranWebOperaciones9APort() {
        return super.getPort(new QName("http://beltran_recu/", "recu_beltran_web_operaciones_9aPort"), RecuBeltranWebOperaciones9A.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuBeltranWebOperaciones9A
     */
    @WebEndpoint(name = "recu_beltran_web_operaciones_9aPort")
    public RecuBeltranWebOperaciones9A getRecuBeltranWebOperaciones9APort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beltran_recu/", "recu_beltran_web_operaciones_9aPort"), RecuBeltranWebOperaciones9A.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECUBELTRANWEBOPERACIONES9A_EXCEPTION!= null) {
            throw RECUBELTRANWEBOPERACIONES9A_EXCEPTION;
        }
        return RECUBELTRANWEBOPERACIONES9A_WSDL_LOCATION;
    }

}
